# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label:  CTA Section
  description: Section with a call to action 
  icon: 'visibility'
  tags:
    - CTA
    - Section

# Defines the structure of this component, as well as the default values
blueprint:
  title: Welcome
  paragraph: Welcome to Jacqueline’s “Almost” Better Than Sex Foods. Fall in love
            with our selection of delectable desserts ranging from tasty banana
            bread to mouth watering caramel sauce. For more information or to
            place an order please contact us.
  button1: Contact

